Calcium imaging monitor
the-virtual-brain/tvb-root pull request #523
Opened 2021-12-08 11:03 UTC by i-Zaak

This continues the #409 locally.

2021-12-09 09:15 UTC, maedoc commented on scientific_library/tvb/simulator/monitors.py
> +class Ca(Monitor):
Something more descriptive is required, as this will be imported into a large notebook namespace..

2021-12-09 09:15 UTC, maedoc commented on scientific_library/tvb/simulator/monitors.py
> +        return '%s(period=%f, voi=%s,with tau_rise=%f and tau_decay=%f)' % (clsname, self.period, self.variables_of_interest.tolist(), self.tau_rise, self.tau_decay)
\n after the tuple opens to keep line length reasonable

2021-12-09 09:30 UTC, maedoc commented on scientific_library/tvb/simulator/monitors.py
> +            self._stock[0,2,:,0] = self._stock[0,2,:,0]*numpy.exp(-self.dt/(self.tau_decay)) + fes * self.dt
if this is a diff eq or has multiple internal state variables, it should be rewritten like the bold as well

2021-12-09 09:31 UTC, maedoc commented on tvb_documentation/demos/calcium_monitor_tutorial/tvb_model_reference/simulation_file/parameter/nuu_parameter_Mouse_512.py
> +class Parameter :
This huge parameter dump here is not ok, especially since there are multiple such files with similar structure and same class names.

2021-12-09 09:33 UTC, maedoc commented on tvb_documentation/demos/calcium_monitor_tutorial/tvb_model_reference/src/Zerlaut_matteo.py
> +class Zerlaut_adaptation_second_order(Zerlaut.Zerlaut_adaptation_second_order):
The parameters here should be documented as traits, not as inline docstrings, to be consistent with the rest of the library datatype/traited classes.

2021-12-09 09:38 UTC, maedoc requested changes
The scope of this PR is far too large.  The monitor with a minimal demo would be appropriate.  the rest of it might make for a nice second PR to add an interesting use case, but given the amount of extra code there (`_simulation_tools.py` etc) I would prefer this be a separate repository even, and of course the data should go into tvb-data.

2022-04-28 07:34 UTC, maedoc commented
any updates @i-Zaak @nuuria8 ?

2022-04-28 07:49 UTC, nuuria8 commented
Hello @i-Zaak @maedoc, at this point I don't know if I have to do something. If so, please let me know.

2022-04-28 07:56 UTC, maedoc commented
- [ ] Please update the code files in the tutorial directory with the clear name and email address of a point of contact for someone who has questions, and preferably who can respond on the TVB mailing list, since I will not be able to answer questions about that code
- [ ] Please respond/make fixes about the comments to the monitor itself

2022-12-05 21:20 UTC, maedoc commented
I'm closing this for now: this is a 114k line diff with no one following up on the above points.

2022-12-05 21:20 UTC, closed without merging