EBR-12 Compatibility with siibra 1.0a14
the-virtual-brain/tvb-root pull request #723
Opened 2024-07-23 12:24 UTC by AdrianValentinCiu

2024-07-23 14:11 UTC, liadomide requested changes
The Siibra Notebooks seems to be broken also.
That one should also be fixed after this upgrade.

2024-07-24 06:29 UTC, romina1601 commented
The latest version of the Julich parcellation (3.1) doesn't seem to have any information about structural or functional connectivity, so it doesn't make sense to show it as an option in the Siibra Connectivity page.
Maybe in the siibra_base.get_last_version() we could get the latest version that _has_ information about the connectivities

2024-07-29 08:51 UTC, AdrianValentinCiu commented
> The latest version of the Julich parcellation (3.1) doesn't seem to have any information about structural or functional connectivity, so it doesn't make sense to show it as an option in the Siibra Connectivity page. Maybe in the siibra_base.get_last_version() we could get the latest version that _has_ information about the connectivities

siibra_base.get_last_version() is needed to return the last version (in this case Julich 3.1). Maybe another methods which returns the latest version that has information about the connectivities should be implemented (in this case for Julich 3.0.3)

2024-07-30 06:41 UTC, liadomide approved these changes

2024-07-30 06:42 UTC, merged